// maps
let latitude;
let longitude
navigator.geolocation.getCurrentPosition(function(position){
    latitude=position.coords.latitude
    longitude=position.coords.longitude
    console.log(latitude+" "+longitude)
})

let map=document.querySelector("iframe")
map.src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d233156.4420025167!2d"+latitude+"!3d"+longitude+"!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1saudi!5e0!3m2!1sru!2sru!4v1756050333011!5m2!1sru!2sru"



//window
let car_content = document.querySelector(".car_content_hidden")
let window_content = ['<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/cars/q5-1.jpg" alt="" class="car_content_img"><img src="style/img/cars/q5-2.webp" alt="" class="car_content_img"><img src="style/img/cars/q5-3.webp" alt="" class="car_content_img"><img src="style/img/cars/q5-4.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>',
    '<div class="car_content_images_container"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"><img src="style/img/1.jpg" alt="" class="car_content_img"></div><a onclick="event.preventDefault();" class="close_button"><img src="style/img/Union (1).png" alt=""></a><p id="p_car_content">charakterisatics1</p>']

let body=document.querySelector("body")
let car_a=document.querySelectorAll(".car_a")
car_a.forEach((item) => {
    
    item.addEventListener("click",function(){
        car_content.classList.remove("car_content_hidden")
        car_content.classList.add("car_content")
        body.style.overflow="hidden";


         car_content.innerHTML=window_content[Number(item.id)]
            let close_button=document.querySelector('.close_button');
            close_button.addEventListener('click',function(){
                car_content.classList.remove('car_content');
                car_content.innerHTML=""
                car_content.classList.add('car_content_hidden');
                body.style.overflow="auto";
                })
            document.addEventListener('keyup',function(event){
                if(event.key=="Escape"){
                    car_content.classList.remove('car_content');
                    car_content.innerHTML=""
                    car_content.classList.add('car_content_hidden');
                    body.style.overflow="auto";
                }
                
                })
    })
});